Added functionality to use sinfonia-tier3 with openrtist python client
cmusatyalab/openrtist pull request #43
Opened 2023-02-09 23:03 UTC by yutianw00

- Created a sinfonia-wrapper.py

- Usage: `.../openrtist_sinfonia/python-client$ ./sinfonia_wrapper.py`

- Additional libraries needed: `sinfonia-tier3` -- `$ pip install [--user] sinfonia-tier3`

- Overall implementation logic:
  - first calls `launchServer` function to use `sinfonia-tier3` trying to deploys the openrtist backend, 
  - then uses `stage` function to keep probing the backend and wait until the backend is up and connects the frontend to it

2023-02-10 18:10 UTC, jaharkes requested changes

2023-02-10 18:10 UTC, jaharkes commented on python-client/sinfonia_wrapper.py
> +from ui import *
What is imported from ui, right now you are calling it through subprocess.run anyway and the 'import *' hides what might actually be used or not.

2023-02-10 18:10 UTC, jaharkes commented on python-client/sinfonia_wrapper.py
> +SINFONIA = "sinfonia"
Is this even used?

2023-02-17 19:44 UTC, yutianw00 commented on python-client/sinfonia_wrapper.py
> +        subprocess.run(cmd)
Right. Maybe we could run the code elsewhere besides my local VM so that we could tell if the EINVAL is a problem with the code or with my local environments.

2023-05-16 18:57 UTC, jaharkes commented
This was merged through commits 00f1648f and 90932d47.

2023-05-16 18:57 UTC, closed without merging